{
 "title": "Rust Servers",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "server",
    "label": "Rust Server",
    "query": "SHOW TAG VALUES WITH KEY=server"
   },
   { "name": "steamid", "label": "SteamID Filter", "query": ".*" }
  ]
 },
 "panels": [
  { "title": "Server Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Online",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "players",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       },
       { "params": [ "Connected" ], "type": "alias" }
      ],
      [
       { "params": [ "joining" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       },
       { "params": [ "Joining" ], "type": "alias" }
      ],
      [
       { "params": [ "queued" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       },
       { "params": [ "Queued" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Server FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "framerate",
     "query": "SELECT min(\"instant\") AS \"Low\", max(\"instant\") AS \"High\" FROM \"framerate\" WHERE (\"server\" =~ /$server$/) AND $timeFilter GROUP BY time($__interval), \"server\" fill(none)",
     "select": [
      [
       { "params": [ "instant" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       },
       { "params": [ "mode" ], "type": "alias" }
      ],
      [
       { "params": [ "instant" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "Min" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/$server$/" }
     ]
    }
   ]
  },
  { "title": "Client Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Client Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_steamid - $tag_ip",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "steamid" ], "type": "tag" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "connection_latency",
     "query": "SELECT mode(\"ping\") AS \"Latency\" FROM \"connection_latency\" WHERE (\"server\" =~ /^$server$/ AND \"steamid\" =~ /^${steamid:raw}$/) AND $timeFilter GROUP BY time($interval), \"ip\", \"steamid\", \"server\" fill(none)",
     "select": [
      [
       { "params": [ "ping" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       },
       { "params": [ "Latency" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "steamid", "operator": "=~", "value": "/^$steamIDFilter$/" }
     ]
    }
   ]
  },
  {
   "title": "Client FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_steamid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "steamid" ], "type": "tag" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "client_performance",
     "query": "SELECT mode(\"fps\") FROM \"client_performance\" WHERE (\"server\" =~ /^$server$/ AND \"steamid\" =~ /^${steamid:raw}$/) AND $timeFilter GROUP BY time($__interval), \"steamid\", \"server\" fill(none)",
     "select": [
      [
       { "params": [ "fps" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "steamid", "operator": "=~", "value": "/^$steamIDFilter$/" }
     ]
    }
   ]
  },
  {
   "title": "Client Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_steamid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "steamid" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "client_performance",
     "query": "SELECT mode(\"memory\") FROM \"client_performance\" WHERE (\"server\" =~ /^$server$/ AND \"steamid\" =~ /^${steamid:raw}$/) AND $timeFilter GROUP BY time($__interval), \"server\", \"steamid\" fill(none)",
     "select": [
      [
       { "params": [ "memory" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "steamid", "operator": "=~", "value": "/^$steamIDFilter$/" }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Data Transfer",
   "type": "timeseries",
   "description": "Megabit per second",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT mode(\"bytes_received\")  / 1024 / 1024 * 8 AS \"Rx\", mode(\"bytes_sent\")  / 1024 / 1024 * 8 AS \"Tx\" FROM \"network\" WHERE (\"server\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval), \"server\" fill(none)",
     "select": [
      [
       { "params": [ "bytes_received" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       },
       { "params": [ " / 1024 / 1024 * 8" ], "type": "math" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       },
       { "params": [ " / 1024 / 1024 * 8" ], "type": "math" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT mode(\"packet_loss\") AS \"Packet Loss\" FROM \"network\" WHERE (\"server\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval), \"server\" fill(none)",
     "select": [
      [
       { "params": [ "packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       },
       { "params": [ "Packet Loss" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Client Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_steamid - $tag_ip",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "steamid" ], "type": "tag" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "connection_latency",
     "query": "SELECT sum(\"packet_loss\") AS \"Packet Loss\" FROM \"connection_latency\" WHERE (\"server\" =~ /^$server$/ AND \"steamid\" =~ /^${steamid:raw}$/) AND $timeFilter GROUP BY time($interval), \"ip\", \"steamid\", \"server\" fill(none)",
     "select": [
      [
       { "params": [ "packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Packet Loss" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "steamid", "operator": "=~", "value": "/^$steamIDFilter$/" }
     ]
    }
   ]
  },
  {
   "title": "Server Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Changes",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$tag_server - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "server" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "memory",
       "query": "SELECT mode(\"allocations\") AS \"Allocations\", derivative(mode(\"collections\"), 5m)  * 100 AS \"GC Pressure\", mode(\"used\") AS \"Memory Usage\" FROM \"memory\" WHERE (\"server\" =~ /$server$/) AND $timeFilter GROUP BY time($__interval), \"server\" fill(none)",
       "select": [
        [
         { "params": [ "allocations" ], "type": "field" },
         {
          "params": [],
          "type": "mode"
         },
         { "params": [ "Allocations" ], "type": "alias" }
        ],
        [
         { "params": [ "collections" ], "type": "field" },
         {
          "params": [],
          "type": "mode"
         },
         { "params": [ "5m" ], "type": "derivative" },
         { "params": [ " * 100" ], "type": "math" },
         { "params": [ "GC Pressure" ], "type": "alias" }
        ],
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "mode"
         },
         { "params": [ "Memory Usage" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "server", "operator": "=~", "value": "/$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Tasks",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$tag_server - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "server" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "tasks",
       "select": [
        [
         { "params": [ "invoke_handler" ], "type": "field" },
         {
          "params": [],
          "type": "mode"
         },
         { "params": [ "Invoke Handler" ], "type": "alias" }
        ],
        [
         { "params": [ "load_balancer" ], "type": "field" },
         {
          "params": [],
          "type": "mode"
         },
         { "params": [ "Load Balancer" ], "type": "alias" }
        ],
        [
         { "params": [ "workshop_skins_queue" ], "type": "field" },
         {
          "params": [],
          "type": "mode"
         },
         { "params": [ "Skins Queue" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "server", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Entities",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_server",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "server" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "entities",
       "query": "SELECT mode(\"count\") AS \"Total Count\" FROM \"entities\" WHERE (\"server\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval), \"server\" fill(none)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mode"
         },
         { "params": [ "Total Count" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "server", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server Updates",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_behaviour.$tag_method",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "server" ], "type": "tag" },
        { "params": [ "behaviour" ], "type": "tag" },
        { "params": [ "method" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "server_update",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Duration" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "server", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Invoke",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_behaviour.$tag_method",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "server" ], "type": "tag" },
        { "params": [ "behaviour" ], "type": "tag" },
        { "params": [ "method" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "invoke_execution",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Duration" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "server", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Object Work Queue",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_behaviour.$tag_method",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "server" ], "type": "tag" },
        { "params": [ "behaviour" ], "type": "tag" },
        { "params": [ "method" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "work_queue",
       "query": "SELECT sum(\"duration\") AS \"Duration\" FROM \"work_queue\" WHERE (\"server\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval), \"server\", \"behaviour\", \"method\" fill(0)",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Duration" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "server", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Misc Timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "alias": "$tag_behaviour.$tag_method",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "server" ], "type": "tag" },
        { "params": [ "behaviour" ], "type": "tag" },
        { "params": [ "method" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rpc_calls",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Duration" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "server", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Console Command",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_command",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "server" ], "type": "tag" },
        { "params": [ "command" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "console_commands",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Duration" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "server", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}